### ISSUE TITLE
Anilist errors in console

### ISSUE THREAD

**Issue by thatsprettygood** [AdollaApp/Adolla#45]
When I start up Adolla, a bunch of errors for AniList start to flow in the console.
I reset my data and it is still happening.

```
[ANILIST] Unable to fetch banner for The God of High School: FetchError: invalid json response body at https://graphql.anilist.co/ reason: Unexpected token < in JSON at position 0
    at C:\Users\username\Downloads\Adolla\node_modules\node-fetch-extra\lib\index.js:254:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  type: 'invalid-json'
}
[ANILIST] Unable to fetch banner for My Hero Academia: FetchError: invalid json response body at https://graphql.anilist.co/ reason: Unexpected token < in JSON at position 0
    at C:\Users\username\Downloads\Adolla\node_modules\node-fetch-extra\lib\index.js:254:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  type: 'invalid-json'
}
[ANILIST] Unable to fetch banner for Berserk: FetchError: invalid json response body at https://graphql.anilist.co/ reason: Unexpected token < in JSON at position 0
    at C:\Users\username\Downloads\Adolla\node_modules\node-fetch-extra\lib\index.js:254:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  type: 'invalid-json'
}
```

**Comment by JipFr** [comment]
Removed!
